system:
  name: Morgan
  log_level: info
  data_dir: /app/data

services:
  llm:
    url: http://llm-service:8001
    model: mistral
    system_prompt: "You are Morgan, a helpful and friendly home assistant AI. You assist with smart home controls, answer questions, and perform various tasks."
    max_tokens: 1000
    temperature: 0.7

  tts:
    url: http://tts-service:8002
    default_voice: morgan_default
    voices:
      morgan_default:
        description: "Default Morgan voice"
        type: "preset"
        preset_id: 12

  stt:
    url: http://stt-service:8003
    model: whisper-large-v3

home_assistant:
  url: http://homeassistant:8123
  token: your_long_lived_access_token
  reconnect_interval: 10

api:
  host: 0.0.0.0
  port: 8000
  cors_origins:
    - "*"
  auth_enabled: false