name: 'Setup NetBird VPN'
description: 'Install and configure NetBird VPN for accessing private resources'
inputs:
  setup-key:
    description: 'NetBird setup key for VPN authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install and configure NetBird VPN
      shell: bash
      run: |
        # Install NetBird
        curl -fsSL https://pkgs.netbird.io/install.sh | sh

        # Start NetBird service (required for daemon mode)
        sudo netbird service install 2>/dev/null || true
        sudo netbird service start

        # Wait for daemon to be ready
        sleep 3

        # Connect to NetBird VPN (required for private Nexus access)
        sudo netbird up \
          --management-url https://vpn.lazarev.cloud \
          --setup-key "${{ inputs.setup-key }}" \
          --log-level info

        # Wait for connection to establish
        sleep 5

        # Verify connection
        if sudo netbird status | grep -q "Connected"; then
          echo "✓ NetBird VPN connected successfully"
          sudo netbird status
        else
          echo "⚠ NetBird connection status unclear, continuing anyway"
          sudo netbird status || true
        fi
