# STT Service Configuration

# Network configuration
host: "0.0.0.0"
port: 8003

# Model configuration
model: "large-v3"
device: "cuda"
language: "en"  # Use specific language or null for auto-detection (faster-whisper doesn't support "auto")

# Audio parameters
sample_rate: 16000
chunk_size: 1024

# VAD (Voice Activity Detection) parameters
vad_enabled: true
vad_threshold: 0.5
vad_min_silence_duration: 0.5

# Logging
log_level: "INFO"
