# TTS Service Configuration - CSM Streaming (HuggingFace transformers)
# Reference: https://huggingface.co/sesame/csm-1b

# Network configuration
host: "0.0.0.0"
port: 8002

# Model configuration - optimized for real-time streaming
model: "csm"  # CSM Streaming (real-time TTS with proper transformers implementation)
device: "cuda"
language: "en"
voice: "default"  # CSM default voice

# Audio parameters - optimized for real-time streaming
speed: 1.0
output_format: "wav"
sample_rate: 24000  # CSM sample rate (24kHz for high quality)

# Streaming configuration - optimized for real-time
streaming_enabled: true
chunk_size: 1024      # Larger chunks for better quality vs latency balance
buffer_size: 4096     # Larger buffer for smoother streaming

# Logging
log_level: "INFO"

# HuggingFace token for model downloads (use environment variable HF_TOKEN instead)
# hf_token: ""  # Set via environment variable: export HF_TOKEN=your_token_here
