# VAD Service Configuration

# Network configuration
host: "0.0.0.0"
port: 8004

# Model configuration
model: "silero_vad"

# Detection parameters
threshold: 0.5
min_speech_duration: 0.25
max_speech_duration: 30.0
window_size: 512
sample_rate: 16000
device: "cpu"

# Logging
log_level: "INFO"
